--local prettier = require("prettier")
--
--prettier.setup({
--    bin = 'prettier', -- or `'prettierd'` (v0.23.3+)
--    filetypes = {
--        "css",
--        "html",
--        "json",
--        "less",
--        "markdown",
--        "scss",
--        "typescript",
--        "typescriptreact",
--        "javascript",
--        "yaml",
--    },
--    cli_options = {
--        tabWidth = 4,
--        arrowParens = 'avoid',
--        bracketSpacing = true,
--        endOfLine = 'lf',
--        printWidth = 100,
--        semi = true,
--        singleQuote = true,
--        trailingComma = 'none',
--        useTabs = false,
--        config_precedence = 'prefer-file'
--    },
--    ["null-ls"] = {
--        condition = function()
--            return prettier.config_exists({
--                -- if `false`, skips checking `package.json` for `"prettier"` key
--                check_package_json = true,
--            })
--        end,
--        runtime_condition = function(params)
--            -- return false to skip running prettier
--            return true
--        end,
--        timeout = 5000,
--    }
--})

-- map('n', '<leader>f', '<Plug>(prettier-format)')
-- map('x', '<leader>f', '<Plug>(prettier-format)')
